version: "3.4"

services:
  sony_qc_data_audit:
    image: 330970998144.dkr.ecr.us-east-1.amazonaws.com/sony_qc_data_audit:${IMAGE_TAG}
    deploy:
      restart_policy:
        condition: "none"
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
      QUALYS_CRAWLER_USER_ID: '${QUALYS_CRAWLER_USER_ID}'
      SPLUNK_GROUP_ID: '${SPLUNK_GROUP_ID}'
    volumes:
      - /var/log/sony_qc_data_audit:/var/log/sony_qc_data_audit
    secrets:
      - source: QC_DATA_AUDIT_SECRETS_${SECRET_VERSION}
        target: /run/secrets/QC_DATA_AUDIT_SECRETS
    labels:
      CI_PIPELINE_ID: '${CI_PIPELINE_ID}'

secrets:
  QC_DATA_AUDIT_SECRETS_${SECRET_VERSION}:
    external: true